### ISSUE TITLE
The code is not working in flutter 2.10

### ISSUE THREAD

**Issue by SiddharthOza00** [MCarlomagno/FaceRecognitionAuth#35]
Does anyone have any idea on how to migrate this code to flutter 2.10 because this code is in flutter 2.7 and there have many syntax changes since then. So can anyone please help? @peterlazar1993 @MCarlomagno

**Comment by KALU-KELECHI-GABRIEL** [comment]
I am also interested in this

**Comment by guruhyes** [comment]
try this :
https://stackoverflow.com/questions/65018588/your-flutter-application-is-created-using-an-older-version-of-the-android-embedd

if platform error try ovverides in pubspec.yaml:
dependency_overrides:
  platform: ^3.1.0

and last is change graddle-wapper.properties version to this
gradle-6.6.1-all.zip

its work for me

**Comment by SiddharthOza00** [comment]
Can you share your code please? @guruhyes

**Comment by guruhyes** [comment]
in android manifest
`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.FaceNet">
    
    <application
        android:name="${applicationName}"
        android:label="FaceNet"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
            
            
            
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
         <meta-data
            android:name="com.google.firebase.ml.vision.DEPENDENCIES"
            android:value="ocr" />
        
    </application>
</manifest>
`
in pubspec

![image](https://user-images.githubusercontent.com/17075371/158041436-1e77e454-2830-47fe-97e7-1c534f94ab3a.png)

in wrapper
![image](https://user-images.githubusercontent.com/17075371/158041456-ac51a619-4c3a-48f2-9ac0-06341c5ffb8e.png)

**Comment by guruhyes** [comment]
in manifest
`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.FaceNet">

    <application
        android:name="${applicationName}"
        android:label="FaceNet"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
         <meta-data
            android:name="com.google.firebase.ml.vision.DEPENDENCIES"
            android:value="ocr" />
        
    </application>
</manifest>`

in wrapper properties
![image](https://user-images.githubusercontent.com/17075371/158041508-ee9f4ae2-a161-47a2-a68d-da75673bef49.png)

in pubspec
![image](https://user-images.githubusercontent.com/17075371/158041517-cddb965d-465c-4d0b-a5e3-c022182246ea.png)

**Comment by SiddharthOza00** [comment]
I did that but its still not working if you have it then can you share the entire code? @guruhyes

**Comment by guruhyes** [comment]
> I did that but its still not working if you have it then can you share the entire code? @guruhyes

can you show the error log?
 or

you can try @KALU-KELECHI-GABRIEL solution

**Comment by SiddharthOza00** [comment]
@KALU-KELECHI-GABRIEL there is still error in app/build.gradle code you shared

**Comment by SiddharthOza00** [comment]
In your project you are using flutter 2.7 not the latest one @KALU-KELECHI-GABRIEL .
Also I am getting these errors
![error](https://user-images.githubusercontent.com/55457720/158648894-bec9e5d7-b9df-4885-928c-1a4e2be50bfd.png)

**Comment by MCarlomagno** [comment]
Hi Guys, sorry for the late answer, I just updated the project to null safety. I'm going to work on the issues found later, thanks for contribuiting!
