### ISSUE TITLE
Null Check operator used on a null value

### ISSUE THREAD

**Issue by hussainint** [MCarlomagno/FaceRecognitionAuth#38]
This error pops out on clicking Sign up Button

**Comment by InsyAravinth** [comment]
Unhandled Exception: 'package:face_net_authentication/services/camera.service.dart': Failed assertion: line 66 pos 9: '_cameraController!.value.previewSize != null': Preview size is null
![image](https://github.com/MCarlomagno/FaceRecognitionAuth/assets/147364558/db5400a0-0a6a-4d5b-8d71-e45e35099fd4)

How to fix the issue while sign up? (first time app opens) @hussainint @MCarlomagno
