### ISSUE TITLE
How to prevent face anti-spoofing?

### ISSUE THREAD

**Issue by doanbh** [MCarlomagno/FaceRecognitionAuth#4]
Good job and good project. 
But I tried it with 1 photo and the app still accepts. Is there any way to prevent this?

**Comment by MCarlomagno** [comment]
Hi! Thanks! Actually thats a good question, for now I couldnt find a model that detects wheter the face came from another screen or not, so I think the best way to prevent it for now is by using the password.

Thanks for participate!

**Comment by Rdp1111** [comment]
https://github.com/Nikit333

**Comment by MCarlomagno** [comment]
Thanks! But for now we will maintain the current functionality
