### ISSUE TITLE
Have you tried to implement without Firebase and just ML kit?

### ISSUE THREAD

**Issue by SushantGautam** [MCarlomagno/FaceRecognitionAuth#5]
https://developers.google.com/ml-kit/migration/android#new
Since we are not using Firebase's cloud component it is wiser to move to the ML kit. 
I don't think there is a library yet.

**Comment by MCarlomagno** [comment]
Hi! thanks for the contribution, this pull request should fix it, I wil check it out and then if works fine, merge it

#21
